### ISSUE TITLE
Build a static version of copy button

### ISSUE THREAD

**Issue by yamamurc** [yamamurc/template-project-with-react#3]

**Comment by yamamurc** [comment]
## To-do
- [ ] Implement SearchableCombobox
  - [ ] Implement unit test for SearchBar
  - [ ] Implement SearchBar
  - [ ] Implement unit test for SearchBar
  - [ ] Implement CharacterTable
    - [ ] Implement unit test for CharacterRow
    - [ ] Implement CharacterRow
  - [ ] Write CSS for these components
